#!/bin/bash 


wrf_model=$1
wrfOutputDsRef=$2
wrfArwDsRef=$3

THISDIR=`pwd`
#THISDIR="/scratch/wrf/scratch/arwpost"
cd $THISDIR
mkdir inputs
mkdir outputs
#xml2namelist -f $wrf_model

cp $wrfOutputDsRef .
dsref2files -i $wrfOutputDsRef -o $THISDIR/inputs -n "http://ci.uchicago.edu/galaxy-es/datasetrefs/wrf/wrf/wrf_output"

if [ "$WRF_ROOT" == "" ]
then
  echo "WRF_ROOT not defined!"
  exit 1
fi

#queue="double"
threads=8
nodes=1
ppn=1

# Soft link to executable and data
ln -sf $WRF_ROOT/$WRF/ARWpost/src/ARWpost.exe
ln -sf $WRF_ROOT/$WRF/ARWpost/fields.plt
ln -sf $WRF_ROOT/$WRF/ARWpost/gribinfo.txt
ln -sf $WRF_ROOT/$WRF/ARWpost/gribmap.txt
ln -sf $WRF_ROOT/$WRF/ARWpost/myLIST
mkdir src
ln -sf $WRF_ROOT/$WRF/ARWpost/src/psadilookup.dat src/psadilookup.dat


cat > arwpost.pbs << EOF
#!/bin/bash

#PBS -l nodes=$nodes:ppn=$ppn
#PBS -l walltime=12:00:00
#PBS -j oe
#PBS -N wrf-$WRF_DOMAINS-$jobId
#PBS -k oe

cd $THISDIR

export MPI_HOME=$MPI_HOME
export PATH=\$MPI_HOME/bin:\$PATH
export LD_LIBRARY_PATH=\$MPI_HOME/lib:\$LD_LIBRARY_PATH

export NETCDF=$NETCDF
export PATH=\$NETCDF/bin:\$PATH
export LD_LIBRARY_PATH=\$NETCDF/lib:\$LD_LIBRARY_PATH

echo "nodefile: \$PBS_NODEFILE"
echo "-----------------------"
cat \$PBS_NODEFILE
cp \$PBS_NODEFILE hostfile.$WRF_DOMAINS-$jobId
echo "-----------------------"

$THISDIR/ARWpost.exe 2>&1
EOF

#./ARWpost.exe 2>&1

files=`ls ./inputs/wrfout_*`
for file in $files
do
  file_name=`basename $file`

  # Starting simulation date
  IYEAR=`expr substr $file_name 12 4`
  IMONTH=`expr substr $file_name 17 2`
  IDAY=`expr substr $file_name 20 2`
  IHOUR=`expr substr $file_name 23 2`

cat > namelist.ARWpost << EOF

&datetime
 start_date = '${IYEAR}-${IMONTH}-${IDAY}_${IHOUR}:00:00'
 end_date = '${IYEAR}-${IMONTH}-${IDAY}_${IHOUR}:00:00'
 interval_seconds = 10800,
 tacc = 0,
 debug_level = 0,
/
&io
 input_root_name = './inputs/wrfout_d01_${IYEAR}-${IMONTH}-${IDAY}_${IHOUR}:00:00'
 output_root_name = './wrfout'
 plot = 'list'
 fields = 'rh2,TH2,Q2,T2,RAINNC,RAINC,GRAUPELNC,SR,height,theta,tc,tk,td,rh,umet,vmet,pressure,dbz,max_dbz,u10m,v10m,wdir,wspd,wd10,ws10,slp,mcape,mcin,lcl,lfc,cape,cin,clfr,geopt'
 fields_file = 'myLIST'
 output_type = 'grads'
 mercator_defs = .true.
/
&interp
 interp_method = 0,
 interp_levels = 1000.,950.,900.,850.,800.,750.,700.,650.,600.,550.,500.,450.,400.,350.,300.,250.,200.,150.,100.,/

 extrapolate = true
 interp_method = 0,

 interp_levels = 1000.,950.,900.,850.,800.,750.,700.,650.,600.,550.,500.,450.,400.,350.,300.,250.,200.,150.,100.,

 interp_levels = 0.25,0.50,0.75,1.00,2.00,3.00,4.00,5.00,6.00,7.00,8.00,9.00,10.0,11.0,12.0,13.0,14.0,15.0,16.0,17.0,18.0,19.0,20.0,
EOF

./ARWpost.exe 2>&1

cat > script.gs << EOF

function main(args)

'open wrfout.ctl'

'set grads off'
'set mpdraw on'
'set mpdset hires'
'set poli on'

'query time'
strLabel= subwrd(result,3)
strTime = subwrd(strLabel,1)

'set T 1'
'clear'

'set gxout shaded'
'run tspBars.gs'
'display T2-273'
'cbarn'

'set rbcols'
'set gxout barb'
'run wndBars.gs'
'set ccolor 2'
'display skip(u10m,4,4);v10m;mag(u10m,v10m)*1.94'

'set strsiz 0.15'
'draw string 1 7.9 Forecast: ' strTime ' 10m Wind (m/s) and 2m Temp (C)'
'set strsiz 0.2'
'draw string 0.05 0.2 http://usefaceit.org'

'printim ./outputs/wrfout_d01_${IYEAR}${IMONTH}${IDAY}Z${IHOUR}.png white x1024 y768'

'quit'

return

EOF

  grads -lbc 'script.gs' 2>&1
done


###################################################

cd $THISDIR
echo "************ $wrfArwDsRef ********************"
#mv output_ARW* outputs/
#
cat > $wrfArwDsRef <<__EOF__
*** TEMPORARY ***
__EOF__
